# Site settings
title: PlanMilT
description: A tactical military planning tool.
baseurl: "" # Root URL, e.g., "/PlanMilT" for GitHub Pages
url: "" # Base URL, e.g., "https://username.github.io"
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
sass:
  style: compressed # Compress CSS output
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - SECURITY.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Dockerfile
  - docker-compose.yml
  - php.ini
  - bd.db
  - logs/
  - SRTM3/
  - elevation_profile.log
  - logfile.log

# Plugins (add as needed)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
