name: Automated Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-tests:
    name: Run PHP Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: pdo_sqlite

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  js-tests:
    name: Run JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Jest
        run: npm test
